const express = require("express");
const db = require("../models");
const router = express.Router();
const { initTable } = require("./initInfo.test");

router.post("/", (req, res) => {
  return res.json({
    subject: [
      {
        number: "004174",
        subject: "컴퓨터공학개론",
        section: "전선",
        degree: "3",
        grade: "C+",
      },
      {
        number: "012101",
        subject: "대학물리(1)",
        section: "M과학",
        degree: "3",
        grade: "B+",
      },
      {
        number: "012103",
        subject: "대학물리실험(1)",
        section: "M과학",
        degree: "1",
        grade: "C+",
      },
      {
        number: "012107",
        subject: "대학화학(1)",
        section: "M과학",
        degree: "3",
        grade: "B+",
      },
      {
        number: "012109",
        subject: "대학화학실험(1)",
        section: "M과학",
        degree: "1",
        grade: "B+",
      },
      {
        number: "012201",
        subject: "대학수학(1)",
        section: "M수학",
        degree: "3",
        grade: "A+",
      },
      {
        number: "002505",
        subject: "현대건축의흐름",
        section: "교선",
        degree: "3",
        grade: "C+",
      },
      {
        number: "002579",
        subject: "컴퓨터SW기초",
        section: "핵교7",
        degree: "3",
        grade: "B+",
      },
      {
        number: "012110",
        subject: "대학화학(2)",
        section: "M과학",
        degree: "3",
        grade: "B+",
      },
      {
        number: "012113",
        subject: "대학화학실험(2)",
        section: "M과학",
        degree: "1",
        grade: "C+",
      },
      {
        number: "012202",
        subject: "대학수학(2)",
        section: "M수학",
        degree: "3",
        grade: "A+",
      },
      {
        number: "101810",
        subject: "C-프로그래밍",
        section: "전선",
        degree: "3",
        grade: "A+",
      },
      {
        number: "002219",
        subject: "서양고전의이해",
        section: "교선",
        degree: "3",
        grade: "C+",
      },
      {
        number: "002580",
        subject: "문제해결과SW프로그래밍",
        section: "핵교7",
        degree: "3",
        grade: "B+",
      },
      {
        number: "012210",
        subject: "확률및통계",
        section: "M수학",
        degree: "3",
        grade: "B+",
      },
      {
        number: "012305",
        subject: "객체지향프로그래밍",
        section: "전선",
        degree: "3",
        grade: "A+",
      },
      {
        number: "013313",
        subject: "논리회로설계및실험",
        section: "전선",
        degree: "4",
        grade: "A+",
      },
      {
        number: "002584",
        subject: "사진예술의이해",
        section: "일교4",
        degree: "3",
        grade: "A+",
      },
      {
        number: "002601",
        subject: "교양일본어(1)",
        section: "일교5",
        degree: "3",
        grade: "B+",
      },
      {
        number: "012206",
        subject: "이산수학",
        section: "M수학",
        degree: "3",
        grade: "A+",
      },
      {
        number: "013312",
        subject: "자료구조및프로그래밍",
        section: "전필",
        degree: "4",
        grade: "A+",
      },
      {
        number: "101408",
        subject: "어셈블리언어및실습",
        section: "전선",
        degree: "3",
        grade: "A+",
      },
      {
        number: "101410",
        subject: "데이터통신",
        section: "전선",
        degree: "3",
        grade: "B+",
      },
      {
        number: "002034",
        subject: "매스컴과현대사회",
        section: "일교2",
        degree: "3",
        grade: "P",
      },
      {
        number: "002530",
        subject: "협상의기술",
        section: "일교1",
        degree: "3",
        grade: "P",
      },
      {
        number: "002592",
        subject: "회계의 이해",
        section: "일교2",
        degree: "3",
        grade: "A+",
      },
      {
        number: "101503",
        subject: "알고리즘분석",
        section: "전필",
        degree: "3",
        grade: "A0",
      },
      {
        number: "101510",
        subject: "컴퓨터구조",
        section: "전필",
        degree: "3",
        grade: "A+",
      },
      {
        number: "101512",
        subject: "프로그래밍언어론",
        section: "전필",
        degree: "3",
        grade: "A+",
      },
      {
        number: "101609",
        subject: "컴퓨터네트워크",
        section: "전선",
        degree: "3",
        grade: "A0",
      },
      {
        number: "101512",
        subject: "디자인씽킹(test)",
        section: "핵교6",
        degree: "3",
        grade: "A+",
      },
      {
        number: "007114",
        subject: "전공기초영어(Ⅱ)",
        section: "전기",
        degree: "2",
        grade: "C+",
      },
      // {
      //   number: '001009',
      //   subject: '영어',
      //   section: '교필',
      //   degree: '3',
      //   grade: 'B+',
      // },
      {
        number: "001012",
        subject: "논리적사고와글쓰기(공학)",
        section: "교필",
        degree: "3",
        grade: "B0",
      },
    ],
    info: [
      { subject: "일교1", degree: "1" },
      { subject: "일교2", degree: "1" },
      { subject: "일교3", degree: "1" },
      { subject: "일교4", degree: "0" },
      { subject: "일교5", degree: "1" },
      { subject: "핵교6", degree: "1" },
      { subject: "핵교7", degree: "1" },
      { subject: "핵교8", degree: "1" },
      { subject: "교필", degree: "6" },
      { subject: "기본/소양/교양 계", degree: "12" },
      { subject: "교선", degree: "6" },
      { subject: "계", degree: "33" },
      { subject: "졸업인정학점", degree: "33" },
      { subject: "수학", degree: "3" },
      { subject: "과학", degree: "15" },
      { subject: "전산", degree: "0" },
      { subject: "계 (일반과정 MSC인정학점)", degree: "24" },
      { subject: "심화과정 MSC인정학점", degree: "24" },
      { subject: "전공", degree: "23" },
      { subject: "전공기초", degree: "2" },
      { subject: "일반선택", degree: "0" },
      { subject: "취득학점", degree: "94" },
      { subject: "졸업인정학점", degree: "132" },
      { subject: "평점", degree: "3.80" },
      { subject: "전공평점", degree: "4.16 점" },
    ],
  });
});

module.exports = router;
